#!/bin/bash

echo "Starting $APP_NAME as `whoami`"
exec gunicorn $APP_NAME.wsgi:application \
  --name $APP_NAME \
  --workers $NUM_WORKERS \
  --user=app \
  --chdir=/home/app/ \
  --bind=0.0.0.0:8080 \
  --proxy_allow_ips='*' \
  --log-level=debug \
  --log-file=-
